# 不要になったので削除する
# version: '3.8'

services:
  nginx:
    image: nginx:1.26.3 # nginx:stableからイメージのバージョンを固定
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    # restart: always ローカルでの開発のため削除

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/
    # restart: always ローカルでの開発のため削除

  mysql:
    image: mysql:9.2.0 # mysql:latestからイメージのバージョンを固定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    # restart: always ローカルでの開発のため削除

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    # restart: always ローカルでの開発のため削除

  mailhog:
    container_name: mailhog_flea_markets
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    # restart: always ローカルでの開発のため削除